name: Build macOS .app

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
          # Ensure you have a requirements.txt file with your dependencies

    - name: Build .app
      run: |
        pyinstaller --onefile --windowed hello_world.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: macOS-app
        path: dist/*.app
